---
title: "Liana Analysis for Myeloid Subset"
author: "Saumya"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
#    number_sections: true # Adds numbers to headers
    css: styles.css
    code_folding: hide
---


```{r, echo = FALSE, results = FALSE, message = FALSE}
# Function to set markdown text color
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
            x)
  } else x
}
```

```{r, echo = FALSE, eval=FALSE, results = FALSE, message = FALSE}
# # Set height of chunk output
# options(width = 60)
# local({
#   hook_output <- knitr::knit_hooks$get('output')
#   knitr::knit_hooks$set(output = function(x, options) {
#     if (!is.null(options$max.height)) options$attr.output <- c(
#       options$attr.output,
#       sprintf('style="max-height: %s;"', options$max.height)
#     )
#     hook_output(x, options)
#   })
# })
```


```{r, results = FALSE, message = FALSE}
# Load required libraries
library(openxlsx)
library(clusterProfiler)
library(msigdbr)
library(org.Hs.eg.db)
library(tidyverse)
library(readxl)
library(rmarkdown)
library(ggplot2)
library(fgsea)
library(tidyverse)
library(magrittr)
library(liana, lib.loc = "/hpc/users/pothus02/.Rlib")

```

```{r, results = FALSE, echo=set_echo, message=FALSE, warning=FALSE}
suffix <- "Seurat"
sampleNames <- c("DART002LC_BL", "DART003LC", "DART005LC", "DART006LC", "DART007LC", "HIV018_CA", "HIV022_CA", "HIV032_CA", "HIV058_LP", "HIV063_LP", "HIV075_LP", "HIV076_LP", "HIV077_LP", "HIV078_LP", "HIV080_LP", "HIV081_LP", "HIV082_LP", "HIV083_LC", "HIV084_LP", "HIV086_LC", "HIV087_LP", "HIV090_LC", "HIV091_LC", "HIV092_LC", "HIV093_LC", "HIV094_LC", "HIV098_LC", "NV144_LP", "NV157_LP_LC", "NV159_LP_LC", "NV161_LC", "NV162_LP_LC", "NV186_LP", "NV201_LP", "NV203_LP", "NV205_LP", "NV212_LC", "NV213_LC", "NV216_LP", "NV222_LP", "NV225_LP", "NV230_LP", "NV234_LC", "NV244_LC", "NV245_LC")

SAMPLE_GROUP <- c("HIV", "HIV", "HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","HIV","Control","Control","Control","Control","Control","Control","Control","Control","Control","Control","Control", "Control", "Control", "Control","Control","Control","Control","Control")
data_dir <- ("../raw_h5/")
projectName <- "Immune HIV vs Control"
h5_string <- "_filtered_feature_bc_matrix.h5"

#Seurat parameters
variables.features <- 2000
nPCs <- 50
```


